import type { AppTheme, ThemeId } from './themeTypes';
import { sleekTokens } from './sleekTokens';

const soft = sleekTokens.colors;
const softBackgroundAlt = '#E0F2FE';
const exportedRadii = {
  sm: sleekTokens.radii.roundedXl,
  md: sleekTokens.radii.rounded2xl,
  lg: sleekTokens.radii.rounded3xl,
  xl: sleekTokens.radii.rounded2_5rem,
  xxl: sleekTokens.radii.roundedTop3rem,
  roundedXl: sleekTokens.radii.roundedXl,
  rounded2xl: sleekTokens.radii.rounded2xl,
  rounded3xl: sleekTokens.radii.rounded3xl,
  rounded1_5rem: sleekTokens.radii.rounded1_5rem,
  rounded2rem: sleekTokens.radii.rounded2rem,
  rounded2_5rem: sleekTokens.radii.rounded2_5rem,
  roundedTop3rem: sleekTokens.radii.roundedTop3rem,
  full: sleekTokens.radii.full,
} satisfies AppTheme['radii'];

const exportedSpacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  p1_5: sleekTokens.spacing.p1_5,
  p3: sleekTokens.spacing.p3,
  p5: sleekTokens.spacing.p5,
  p6: sleekTokens.spacing.p6,
  px4: sleekTokens.spacing.px4,
  px5: sleekTokens.spacing.px5,
  px6: sleekTokens.spacing.px6,
  py1_5: sleekTokens.spacing.py1_5,
  py2: sleekTokens.spacing.py2,
  py2_5: sleekTokens.spacing.py2_5,
  py4: sleekTokens.spacing.py4,
  py5: sleekTokens.spacing.py5,
  pt12: sleekTokens.spacing.pt12,
  pb32: sleekTokens.spacing.pb32,
  gap2: sleekTokens.spacing.gap2,
  gap3: sleekTokens.spacing.gap3,
  gap4: sleekTokens.spacing.gap4,
  gap6: sleekTokens.spacing.gap6,
} satisfies AppTheme['spacing'];

export const themes: Record<ThemeId, AppTheme> = {
  'soft-sky': {
    id: 'soft-sky',
    name: 'Soft Sky',
    copyTone: 'playful',
    colors: {
      background: soft.background,
      backgroundAlt: softBackgroundAlt,
      card: soft.card,
      cardForeground: soft.cardForeground,
      cardMuted: soft.muted,
      foreground: soft.foreground,
      primary: soft.primary,
      primaryForeground: soft.primaryForeground,
      secondary: soft.secondary,
      secondaryForeground: soft.secondaryForeground,
      accent: soft.accent,
      accentForeground: soft.accentForeground,
      text: soft.foreground,
      muted: soft.muted,
      mutedText: soft.mutedForeground,
      border: soft.border,
      input: soft.input,
      ring: soft.ring,
      success: soft.chart1,
      warning: soft.secondary,
      danger: soft.destructive,
      destructive: soft.destructive,
      tabBar: soft.card,
      tabActive: soft.primary,
      tabInactive: soft.mutedForeground,
      overlay: 'rgba(45,52,54,0.22)',
      buttonText: soft.primaryForeground,
      heroAccent: softBackgroundAlt,
      cardOverlay: soft.card,
      highlight: soft.muted,
      globeWater: soft.primary,
      globeLand: soft.chart1,
      globePin: soft.primaryForeground,
      globePinSelected: soft.secondary,
      chart1: soft.chart1,
      chart2: soft.chart2,
      chart3: soft.chart3,
      chart4: soft.chart4,
      chart5: soft.chart5,
    },
    gradients: {
      screen: [soft.background, softBackgroundAlt],
      hero: [sleekTokens.alpha.primary10, sleekTokens.alpha.secondary10],
      card: [soft.card, soft.background],
    },
    radii: exportedRadii,
    spacing: exportedSpacing,
    shadows: {
      card: {
        shadowColor: soft.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
      },
      floating: {
        shadowColor: soft.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 20,
        elevation: 6,
      },
    },
    typography: {
      titleSize: 30,          // text-3xl
      headingSize: 24,        // text-2xl
      bodySize: 16,           // text-base
      captionSize: 12,        // text-xs
      temperatureSize: 96,    // text-8xl
      titleWeight: '700',
      bodyWeight: '500',
      temperatureWeight: '700',
    },
    buttons: {
      primary: {
        background: soft.primary,
        text: soft.primaryForeground,
        border: soft.primary,
      },
      secondary: {
        background: soft.secondary,
        text: soft.secondaryForeground,
        border: soft.secondary,
      },
      ghost: {
        background: 'transparent',
        text: soft.primary,
        border: 'transparent',
      },
    },
    weatherMoodStyle: {
      sunny: 'sunny-little-win',
      cloudy: 'soft-cloudy-morning',
      rainy: 'umbrella-quest',
      stormy: 'dramatic-sky',
      snowy: 'snow-globe-mode',
    },
    backgroundStyle: {
      type: 'soft',
      texture: 'cloudy',
    },
  },
  'night-cloud': {
    id: 'night-cloud',
    name: 'Night Cloud',
    copyTone: 'cozy',
    colors: {
      background: '#101628',
      backgroundAlt: '#1D2240',
      card: '#1B2238',
      cardForeground: '#F3F5FF',
      cardMuted: '#252A48',
      foreground: '#F3F5FF',
      primary: '#A99CFF',
      primaryForeground: '#101628',
      secondary: '#6DD6E8',
      secondaryForeground: '#101628',
      accent: '#F6B7FF',
      accentForeground: '#101628',
      text: '#F3F5FF',
      muted: '#252A48',
      mutedText: '#AEB7D6',
      border: '#343A5D',
      input: '#1B2238',
      ring: '#A99CFF',
      success: '#71D6A4',
      warning: '#F5CF72',
      danger: '#FF7A9A',
      destructive: '#FF7A9A',
      tabBar: '#171D31',
      tabActive: '#C8C1FF',
      tabInactive: '#7E88A8',
      overlay: 'rgba(7, 10, 20, 0.48)',
      buttonText: '#101628',
      heroAccent: '#30265E',
      cardOverlay: '#202842',
      highlight: '#332D5C',
      globeWater: '#5549A8',
      globeLand: '#6DD6E8',
      globePin: '#F3F5FF',
      globePinSelected: '#F6B7FF',
      chart1: '#6DD6E8',
      chart2: '#FF7A9A',
      chart3: '#F5CF72',
      chart4: '#A99CFF',
      chart5: '#F3F5FF',
    },
    gradients: {
      screen: ['#101628', '#1D2240', '#261D42'],
      hero: ['#30265E', '#604B96', '#101628'],
      card: ['#232A44', '#171D31'],
    },
    radii: exportedRadii,
    spacing: exportedSpacing,
    shadows: {
      card: {
        shadowColor: '#A99CFF',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.18,
        shadowRadius: 24,
        elevation: 5,
      },
      floating: {
        shadowColor: '#C8C1FF',
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.24,
        shadowRadius: 32,
        elevation: 9,
      },
    },
    typography: {
      titleSize: 34,
      headingSize: 24,
      bodySize: 16,
      captionSize: 13,
      temperatureSize: 76,
      titleWeight: '700',
      bodyWeight: '500',
      temperatureWeight: '700',
    },
    buttons: {
      primary: {
        background: '#C8C1FF',
        text: '#101628',
        border: '#C8C1FF',
      },
      secondary: {
        background: '#252A48',
        text: '#F3F5FF',
        border: '#3A4169',
      },
      ghost: {
        background: 'transparent',
        text: '#C8C1FF',
        border: '#3A4169',
      },
    },
    weatherMoodStyle: {
      sunny: 'moonlit-clear',
      cloudy: 'blanket-clouds',
      rainy: 'window-rain',
      stormy: 'thunder-cozy',
      snowy: 'quiet-snowfall',
    },
    backgroundStyle: {
      type: 'dark',
      texture: 'glow',
    },
  },
  'race-day': {
    id: 'race-day',
    name: 'Race Day',
    copyTone: 'racing',
    colors: {
      background: '#090A0D',
      backgroundAlt: '#17191F',
      card: '#14161B',
      cardForeground: '#FFFFFF',
      cardMuted: '#20232A',
      foreground: '#FFFFFF',
      primary: '#F21F3A',
      primaryForeground: '#FFFFFF',
      secondary: '#FFFFFF',
      secondaryForeground: '#090A0D',
      accent: '#FFCD2E',
      accentForeground: '#090A0D',
      text: '#FFFFFF',
      muted: '#20232A',
      mutedText: '#A8ADB7',
      border: '#333842',
      input: '#14161B',
      ring: '#F21F3A',
      success: '#21D07A',
      warning: '#FFCD2E',
      danger: '#F21F3A',
      destructive: '#F21F3A',
      tabBar: '#111318',
      tabActive: '#F21F3A',
      tabInactive: '#8B909B',
      overlay: 'rgba(0, 0, 0, 0.56)',
      buttonText: '#FFFFFF',
      heroAccent: '#2B1118',
      cardOverlay: '#1B1E25',
      highlight: '#2B1118',
      globeWater: '#1F2530',
      globeLand: '#F21F3A',
      globePin: '#FFFFFF',
      globePinSelected: '#FFCD2E',
      chart1: '#21D07A',
      chart2: '#F21F3A',
      chart3: '#FFCD2E',
      chart4: '#FFFFFF',
      chart5: '#A8ADB7',
    },
    gradients: {
      screen: ['#090A0D', '#17191F', '#2B1118'],
      hero: ['#F21F3A', '#17191F', '#090A0D'],
      card: ['#20232A', '#14161B'],
    },
    radii: exportedRadii,
    spacing: exportedSpacing,
    shadows: {
      card: {
        shadowColor: '#F21F3A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.16,
        shadowRadius: 16,
        elevation: 4,
      },
      floating: {
        shadowColor: '#F21F3A',
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 0.28,
        shadowRadius: 26,
        elevation: 8,
      },
    },
    typography: {
      titleSize: 33,
      headingSize: 23,
      bodySize: 16,
      captionSize: 12,
      temperatureSize: 74,
      titleWeight: '700',
      bodyWeight: '500',
      temperatureWeight: '700',
    },
    buttons: {
      primary: {
        background: '#F21F3A',
        text: '#FFFFFF',
        border: '#F21F3A',
      },
      secondary: {
        background: '#FFFFFF',
        text: '#090A0D',
        border: '#FFFFFF',
      },
      ghost: {
        background: 'transparent',
        text: '#FFFFFF',
        border: '#333842',
      },
    },
    weatherMoodStyle: {
      sunny: 'green-flag-sun',
      cloudy: 'mixed-conditions',
      rainy: 'wet-tyre-alert',
      stormy: 'safety-car-sky',
      snowy: 'cold-start',
    },
    backgroundStyle: {
      type: 'sport',
      texture: 'track',
    },
  },
};

export const defaultThemeId: ThemeId = 'soft-sky';

export function getThemeById(themeId: string): AppTheme {
  return themes[themeId as ThemeId] ?? themes[defaultThemeId];
}
